apiVersion: v1
kind: Pod
metadata:
  name: init-pod
  labels:
    app: initializer
spec:
  initContainers:
    - name: init-ctr
      image: busybox
      command: ['sh', '-c', 'until nslookup k8sbook; do echo waiting for k8sbook service; sleep 1; done; echo Service found!']
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80