apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader
rules:
  - verbs:
      - list
      - get
      - watch
    resources:
      - pods
      - pods/log
    apiGroups:
      - ""