apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
rules:
  - verbs:
      - get
      - watch
      - list
    resources:
      - pods
      - pods/log
    apiGroups:
      - ""