apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-admin-binding
roleRef:
  kind: Role
  name: service-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: User
    name: mohyehia
  - kind: User
    name: demo
  - kind: ServiceAccount
    name: test-sa