apiVersion: v1
kind: LimitRange  # this kind is namespaced
metadata:
  name: limit-range
spec:
  limits:
    - type: Pod
      min:
        cpu: 50m
        memory: 5Mi
      max:
        cpu: '2'
        memory: 2Gi
    - type: Container
      defaultRequest: # will be applied if we didn't specify the request for the container
        cpu: 100m
        memory: 10Mi
      default: # will be applied if we didn't specify the limits for the container
        cpu: 200m
        memory: 100Mi
      min:
        cpu: 50m
        memory: 5Mi
      max:
        cpu: '1'
        memory: 1Gi
      maxLimitRequestRatio:
        cpu: '4'
        memory: '10'
    - type: PersistentVolumeClaim
      min:
        storage: 1Gi
      max:
        storage: 10Gi