apiVersion: v1
kind: Namespace
metadata:
  name: nginx-namespace
  labels:
    env: development
---
apiVersion: v1
kind: Pod
metadata:
  namespace: nginx-namespace
  name: nginx-pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80