global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'Host Monitoring'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:9100']
        labels:
          application: 'Host Monitoring'

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['alert-manager:9093']

rule_files:
  - alerting-rules.yml