apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  volumes:
    - name: secret-vol
      secret:
        secretName: sample-secret
  containers:
    - name: nginx-pod
      image: nginx
      volumeMounts:
        - mountPath: /etc/secret-vol
          name: secret-vol
          readOnly: true