apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: staging
configMapGenerator:
  - name: app-config
    literals:
      - env=staging
      - LOG_LEVEL=debug
  - name: credentials
    files:
      - credentials=creds.txt