# At this approach by using `Volumes` & `VolumeMounts` we can mount the Pod data to the container
# by using the volume type = 'emptyDir: {}'
# But if the pod is failed or restarted, then all data is lost
# Also, if we have multiple replicas of the same pod, then the other pods can't access the data of the pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo-ctr
          image: mongo:7.0.0
          args: ['--dbpath', '/data/db']
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
          volumeMounts:
            - mountPath: /data/db
              name: mongo-volume
      volumes:
        - name: mongo-volume
          emptyDir: {}