# If we need to store tha data inside the node instead of inside the pod, we can use `hostPath` instead of `emptyDir`
# hostPath is pointing to the directory of where the data will be live inside the node of the pod. (minikube in our case)
# But, if we have multiple nodes then other Pods inside other nodes can't access the data.
# Also, if the node is deleted or restarted, then all data inside this node will be lost.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo-ctr
          image: mongo:7.0.0
          args: ['--dbpath', '/data/db']
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
          volumeMounts:
            - mountPath: /data/db
              name: mongo-volume
      volumes:
        - name: mongo-volume
          hostPath:
            path: /data