apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
spec:
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: local-pvc
  containers:
    - name: ubuntu-ctr
      image: ubuntu:latest
      command:
        - /bin/bash
        - "-c"
        - "sleep 60m"
      volumeMounts:
        - mountPath: /data
          name: data