apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  labels:
    app: fluentd-logging
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      nodeSelector:
        type: logging-node
      containers:
        - name: fluentd-elasticsearch
          image: quay.io/fluentd_elasticsearch/fluentd:latest
          resources:
            limits:
              memory: 200Mi
            requests:
              memory: 200Mi
              cpu: 100m
          volumeMounts:
            - mountPath: /var/log
              name: log-vol
      terminationGracePeriodSeconds: 30
      volumes:
        - name: log-vol
          hostPath:
            path: /var/log
