apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    env: test
spec:
#  ipFamilyPolicy: PreferDualStack
#  ipFamilies:
#    - IPv4
#    - IPv6
  type: NodePort
  ports:
    - port: 8082
      targetPort: 80
      nodePort: 30000
      protocol: TCP
  selector:
    app: nginx