version: '3.8'
services:
  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - '9090:9090'
    extra_hosts:
      - host.docker.internal:host-gateway
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./volumes/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./volumes/prometheus/alerting-rules.yml:/etc/prometheus/alerting-rules.yml

  grafana:
    image: grafana/grafana-oss:10.1.2
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./volumes/grafana/data:/var/lib/grafana
      - ./volumes/grafana/provisioning/datasources/:/etc/grafana/provisioning/datasources/
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

  alert-manager:
    image: bitnami/alertmanager:latest
    container_name: alert-manager
    ports:
      - '9093:9093'
    volumes:
      - ./volumes/alert-manager/config.yml:/opt/bitnami/alertmanager/conf/config.yml
    restart: on-failure

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - '1025:1025' # SMTP server port
      - '8025:8025' # HTTP server port

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter-ctr
    ports:
      - '9100:9100'
    restart: on-failure